### ISSUE TITLE
Response of POST requests not handled properly

### ISSUE THREAD

**Issue by snitchashor** [EvELabs/oauth2-eveonline#1]
POST requests seem to give an empty response and a status code, which is not handled correctly by the provider. Throws an error which says something like "200: Fitting saved" or similar.

**Comment by snitchashor** [comment]
Sorry, the status code is 201 not 200. Right now I use the following workaround for checkResponse:

```
    if (false === is_array($data)) {
        if ($response->getStatusCode() != 201) {
            throw new IdentityProviderException(
                $response->getReasonPhrase(),
                $response->getStatusCode(),
                $response
            );
        }
    }
```

**Comment by okwinza** [comment]
@snitchashor Thanks for reporting, this should be fixed now, please reopen if the issue is still present.
